CREATE TABLE bolsista (
    ID INTEGER PRIMARY KEY UNIQUE NOT NULL,
    Nome_Bolsista VARCHAR NOT NULL,
    RG VARCHAR UNIQUE NOT NULL,
    CPF VARCHAR UNIQUE NOT NULL,
    Curso VARCHAR NOT NULL,
    Matricula VARCHAR NOT NULL,

);